### ISSUE TITLE
Arecorder states

### ISSUE THREAD

**Issue by thomas-hermann** [interactive-sonification/pya#10] opened 2019-10-02 19:18 UTC
- To my opinion, Arecorder states should be changed from current words (stop/record/pause) to 'stopped', 'recording', 'paused'.

- current_state attribute should be refactored to state, and to simply drop the attribute state which currently holds a dict.
self.current_state = self.state['pause'] --> self.state = 'paused'

- as by-product, users can more easily read code, e.g. they can write
if ar.state == "paused":
    pass
instead of 
if ar.current_state = 2: 
   pass

any objection?

**Comment by wiccy46** [comment] 2019-10-02 19:38
Hi, yes. That makes sense. But I still think it makes sense to have the states as a variable or a class. 

@Alex, what do you think? 

The issue I think making the states a separate class is whether it creates potential error if other inherit Arecorder for a new class

Thanks

Jiajun

**Comment by wiccy46** [comment] 2019-10-02 19:58
How about use nested class, which creates a state class within Arecorder? Or this is considered bad practice .

**Comment by aleneum** [comment] 2019-10-04 07:39
Best practise for such cases are Enums which are natively supporten by Python 3.4+:

```python
from enum import Enum

class State(Enum):
    ERROR = -1
    UNKNOWN = 0
    STOPPED = 1
    RECORDING = 2
    PAUSED = 3

class Recorder:

   def __init__(self):
       self.state = State.UNKNOWN

r = Recorder()
r.state  # >>> <State.UNKNOWN: 0>

# switch case in Python

state_behaviour = {
    State.ERROR: process_error,
    State.UNKNOWN: raise_error,
    State.STOPPED: play
    # ...
}

state_behaviour[r.state](*args, **kwargs)
```

If `UNKNOWN` cannot happen by design, I'd suggest using `ERROR=0`. This way error checks get more convenient:

```python
if not r.state:
   # something bad happened!
```

**Comment by aleneum** [comment] 2019-10-04 07:46
I would avoid strings for comparison and access wherever possible. Bugs in string comparisons are hard to track (`state == 'stoped'`) and string access in dicts becomes unnecessarily complex (as @thomas-hermann mentioned) or leads to 'suboptimal' less comprehensible practices (`state == 1` instead of `state == states['paused']`).

**Comment by wiccy46** [comment] 2019-10-04 08:36
So if I make inherit Arecorder in a new project, and override some of the methods involving checking the state. Will that causes exception since State is not imported in the new file.

**Comment by aleneum** [comment] 2019-10-04 08:50
> So if I make inherit Arecorder in a new project, and override some of the methods involving checking the state.

If you want to use it, you have to import it. You could to `from pya.recorder import Recorder, State` or in case you deal with multiple Enums `from pya.recorder import State as RecorderState`

>  self.states = State() 

what's the purpose of instantiation here? Enums are commonly static. If you want to assign it to `Recorder` i'd suggest a static class attribute instead:

```python
from enum import Enum

class State(Enum):
    ERROR = -1
    UNKNOWN = 0
    STOPPED = 1
    RECORDING = 2
    PAUSED = 3

class Recorder:

     STATES = State
     def __init__(self):
        self.state = self.STATES.UNKNOWN

r = Recorder()
r.STATES  #  >>> <enum 'State'>
r.STATES.UNKNOWN  # >>> <State.UNKNOWN: 0>
```

**Closed** 2019-10-04 10:20 UTC
Labels: enhancement

**Comment by thomas-hermann** [comment] 2019-10-04 17:19
cool, I like the Enum solution :-) 
I wonder what the oldest compatible pre-python3.4 version would have been without Enum (no need to change anything, just curious )

**Comment by wiccy46** [comment] 2019-10-04 20:38
@thomas-hermann , actually we reverted back to using a flag namely self._recording. As we concluded that it is over-engineering for a rather simply case. Also, we feel that resume is not necessary. We just rotate between record(), pause() and stop(). Where record and pause switch the flag. Stop also deal with the recordings and record_buffer in addition to setting the flag.

**Comment by thomas-hermann** [comment] 2019-10-05 17:15
perfect. removed dangling mention of resume in pya examples. issue closed.
